### ISSUE TITLE
Add upper bound to `errors` for `orchestrate` package

### ISSUE THREAD

**Issue by erochest** [erochest/orchestrate#1]
`errors-2.0` will switch to use `ExceptT` instead of `EitherT`.  If that
will break your package then add an upper bound of `errors < 2.0` to
your dependencies.

**Comment by Gabriel439** [comment]
Thanks!  Also, don't forget to upload this to Hackage when you get a chance.  There is no hurry, as there are a few weeks to go before I upload `errors-2.0` to Hackage

**Comment by erochest** [comment]
:+1:
